# Generated by Django 6.0.6 on 2026-07-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='board',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='current_turn',
            field=models.CharField(default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='room',
            name='winner',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
